### ISSUE TITLE
Backend fails without gems

### ISSUE THREAD

**Issue by wrightj5** [petems/petems-hiera_vault#18]
Ideally this function doesn't completely fail if the required gems are missing.

I think it would be better for it to just skip over the backend - that way a user can keep a default set of Vault information in their managed hiera.yaml file and not need to worry about having the required gems in place before that hiera.yaml file is deployed.

It's helped us internally as we deploy our Hiera file via r10k. Now I can r10k the same file to X amount of Puppetservers, and the ones with Vault installed will use the backend and the ones without can simply continue on as normal using the other backends defined.

**Comment by jayabalan1992** [comment]
Use '**puppetserver install debouncer**' to install debouncer gems. 
Thereafter it worked for me.

**Comment by wrightj5** [comment]
I think that Puppet should be installing this for us.

**Comment by wrightj5** [comment]
Yeah, check the PR that I raised. 
The gem needs to be installed using the puppetserver binary **and** the gem binary in /opt/puppetlabs

**Comment by petems** [comment]
Note added to Readme (8b54fbe735d6bb9862c2f2eca6853e84b3518947)
