### ISSUE TITLE
can't use standby node

### ISSUE THREAD

**Issue by maxadamo** [petems/petems-hiera_vault#27]
I have a Vault cluster and, since hiera is read-onyl, I wanted to use either active and standby node. 

I do not have an in depth knowledge of Vault, hence I am not sure if this is  a limitation of Vault, a problem with my configuration a problem with hiera_vault, a problem the ruby gem... a problem with something else :smiley:

**Comment by fuero** [comment]
Vault will point requests to standby nodes to the active node. All nodes in the cluster should be unsealed though.

This is likely a Vault configuration issue.

Have a look at [Hashicorp's docs](https://www.hashicorp.com/resources/hashicorp-vault-administrative-guide) for details.

**Comment by maxadamo** [comment]
@fuero  Of course they're both unsealed and Consul tells me who's the active. I said that I don't know all the tricks with Vault, not that I'm clueless :smile:  But THANKS for the hint. 
Now I see the problem and I'm remembering something:
```
Error listing secrets engines: redirect would cause protocol downgrade
```
but if all the requests still go to the master I don't see the point. 

As far as you know, is it possible - like in Consul - to eventually read stale entries from the standby? 
If I write very rarely to the master(which is the use case of Puppet hiera), I don't see the point of force reading from the master.

**Comment by maxadamo** [comment]
I'm gonna close it. Since this was a configuration issue, everything else is not in topic here.
