### ISSUE TITLE
Feature Request: Renew Token Key

### ISSUE THREAD

**Issue by joaquin386** [petems/petems-hiera_vault#33]
Hi 

It would be nice if there was an option like on consul-template to renew the token (once we have manually create it for the first time). Just an idea. 

Thanks

Joaquin

**Comment by fuero** [comment]
With HashiCorp adding an [agent mode](https://www.vaultproject.io/docs/agent/) to Vault this and support for other login mechanisms for Vault are likely to become a non-issue.

It's then the Vault Agent's job to take care of this.

**Comment by joaquin386** [comment]
Thx for the info @fuero Did the vault agent config and it is working nicely, so there is no reason for this issue to still be open.
