### ISSUE TITLE
Token Field does not Support JSON Files

### ISSUE THREAD

**Issue by joaquin386** [petems/petems-hiera_vault#34]
Hi Peter

token: The token to authenticate with Vault, also read as ENV["VAULT_TOKEN"] or a full path to the file with the token (eg. /etc/vault_token.txt). When bootstrapping, you can set this token as IGNORE-VAULT and the backend will be stubbed, which can be useful when bootstrapping.

From vault agent and the sink the format for the file (/etc/vault/.vault_token) is the following:
{"token":"s.XXXXXXXXXXX","accessor":"XXXXXXXXXXXXXX","ttl":300,"creation_time":"2019-02-25T11:59:35.172939383Z","creation_path":"sys/wrapping/wrap","wrapped_accessor":""}

It can only read files with the plain token value in it not with the vault agent info from above.
https://www.vaultproject.io/docs/agent/autoauth/index.html

Easy to have another script reading that file and duping the info on another file but then you will have an inconsistency for couple of seconds,so it is better to make a change on the code.

BR

Joaquin

Vault agent Config
```
pid_file = "/etc/vault/pidfile"

auto_auth {
  method "approle" {
    mount_path = "auth/approle"
    config = {
      role_id_file_path = "/etc/vault/role_id.txt"
      secret_id_file_path = "/etc/vault/secret_id.txt"
      remove_secret_id_file_after_reading = false
    }
  }
  sink "file" {
    wrap_ttl = "5m"
    config = {
      path = "/etc/vault/.vault_token"
    }
  }
}
```

**Comment by petems** [comment]
Ah nice idea actually... 

Here's my plan

Default to assuming it's just the token string as a plain text file (to not break existing users)
Add a new field asking for the format
If set to auto_auth it'll read the HCL and look for the token file part of the config

Sound good?

**Comment by joaquin386** [comment]
Totally agree, has to make it compatible with current use cases which 100% of the time uses the token on the hiera.yaml file or the plain text token on a file

**Comment by fuero** [comment]
When trying this with vault 1.0.3 it works exactly as expected - Vault writes just the token to the sink file specified.

Config:

```
pid_file = "/run/vault/puppet-agent.pid"

auto_auth {
        method "approle" {
                config = {
			role_id_file_path = "/etc/puppetlabs/vault/vault-role-id"
			secret_id_file_path = "/etc/puppetlabs/vault/vault-secret-id"
			remove_secret_id_file_after_reading = false
                }
        }

        sink "file" {
                config = {
                        path = "/etc/puppetlabs/vault/vault-token"
                }
        }
}
```

**Comment by joaquin386** [comment]
Does you token gets renew? Thats the reason I added wrap_ttl = "5m", cause if not it was not renewing.

**Comment by fuero** [comment]
From the docs, emphasis mine:

> wrap_ttl (string or integer: optional) - If specified, the written token will be response-wrapped by the agent. This is more secure than wrapping by sinks, **but does not allow the agent to keep the token renewed or automatically reauthenticate when it expires**. Rather than a simple string, the written value will be a JSON-encoded SecretWrapInfo structure. Values can be an integer number of seconds or a stringish value like 5m.

I did not verify the renewal - but that should depend on the token's ttl.

**Comment by joaquin386** [comment]
```
vault write auth/approle/role/puppetserver \
    policies=puppet \
    token_ttl=30m \
    token_max_ttl=30m
```
Simple config ....... will see if upgrade to 1.0.3 will do anything better

**Comment by joaquin386** [comment]
So far have done your changes and the token is a string so for now seem fine .... will check for the renewal
