### ISSUE TITLE
How to protect the token?

### ISSUE THREAD

**Issue by xaque208** [petems/petems-hiera_vault#35]
I'm reviewing this code as a potential move away from hiera-eyaml, but I'm not clear how to protect the token in the hiera.yaml file.  Since this file is committed to the repo in my environment, I don't see an opportunity to template out this file due to the environments.  Please, can you offer a bit of guidance here?

**Comment by petems** [comment]
It's preferable to set the hiera token as an environmental variable or configure it in a file that's managed by [consul-tempalte](https://github.com/hashicorp/consul-template)

> token: The token to authenticate with Vault, also read as ENV["VAULT_TOKEN"] or a full path to the file with the token (eg. /etc/vault_token.txt). When bootstrapping, you can set this token as IGNORE-VAULT and the backend will be stubbed, which can be useful when bootstrapping.

**Comment by xaque208** [comment]
And to be clear, this will be the environment of the puppetserver, correct?

**Comment by petems** [comment]
Yes, all the lookups are done Puppetserver side. You can even use the PKI backend as auth to generate the tokens, using the puppetserver certs as the auth method.

**Comment by xaque208** [comment]
This all works by specifying the token file as in the `token` field of the `hiera.yaml`.  Thank you for the information.
