### ISSUE TITLE
handshake_failure

### ISSUE THREAD

**Issue by petersutty** [petems/petems-hiera_vault#39]
when trying to read from vault I am getting following on puppet agent:
 $ sudo puppet agent -tv --tags test
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Lookup of key 'libnss-ldap_secret' failed: [hiera-vault] Skipping backend. Configuration error: Received fatal alert: handshake_failure (file: /etc/puppetlabs/code/environments/stretch/modules/test/manifests/init.pp, line: 5, column: 13) on node kicktest.domain.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

tcpdump confirms it is handshake failure

puppetserver -v
puppetserver version: 5.3.9

puppet module list | grep vault
davealden-hiera_vault (v0.9.0) - that is the 0.1.0 version from git

puppetserver gem list

*** LOCAL GEMS ***

aws-sigv4 (1.0.3)
columnize (0.9.0)
debouncer (0.2.2)
deep_merge (1.0.1)
did_you_mean (default: 1.0.1)
fast_gettext (1.1.2)
gettext (3.2.2)
hiera-eyaml (3.0.0, 2.1.0)
hiera-vault (0.2.2)
highline (1.6.21)
hocon (1.2.5)
jar-dependencies (default: 0.3.12)
jruby-openssl (0.9.21 java)
jruby-readline (1.2.2 java)
json (1.8.3 java)
linecache (1.3.1 java)
locale (2.1.2)
minitest (default: 5.4.1)
multi_json (1.13.1)
net-telnet (default: 0.1.1)
optimist (3.0.0)
power_assert (default: 0.2.3)
psych (2.2.4 java)
puppetserver-ca (1.2.1)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
ruby-debug (0.10.6)
ruby-debug-base (0.10.6 java)
semantic_puppet (0.1.3, 0.1.2)
test-unit (default: 3.1.1)
text (1.3.1)
trollop (2.9.9)
vault (0.11.0)

puppetserver ruby --version
jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-8u222-b10-1~deb9u1-b10 +jit [linux-x86_64]

/etc/puppetlabs/puppet/hiera.yaml
version: 5
hierarchy:
  - name: "Hiera-vault lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - ".*secret$"
        - ".*vault$"
      ssl_verify: false
      ssl_pem_file: /etc/puppetlabs/puppet/ssl/ssl_pem_file.pem
      ssl_ca_cert: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
      address: https://vault.domain.com:8200
      token: s.x6kVhjgf67gjM2p4UXlzBB65jg876876bSFfC4hn
      default_field: value
      mounts:
        generic:
          - secret/puppet/%{::environment}/
          - secret/puppet/

cat /etc/puppetlabs/code/environments/stretch/modules/test/manifests/init.pp
class test {

  $secret = lookup({"name" => "libnss-ldap_secret", "value_type" => String, "merge" => "first"})          
  notify {"testing vault ${secret}":}
  file { '/tmp/test':
        content => $secret,
  }

  notify {"testing vault1":}
  file { '/tmp/test1':
        content => lookup({"name" => "libnss-ldap_secret", "value_type" => String, "merge" => "first"}),

  }
}

PUPPET LOOKUP AND CURL WORKS

puppet lookup libnss-ldap_secret --explain
Searching for "lookup_options"
  Global Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
    Hierarchy entry "Hiera-vault lookup"
      No such key: "lookup_options"
      [hiera-vault] Skipping hiera_vault backend because key 'lookup_options' does not match confine_to_keys
  Environment Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/code/environments/stretch/hiera.yaml"
    Merge strategy hash
      Hierarchy entry "Per-node data (yaml version)"
        Path "/etc/puppetlabs/code/environments/stretch/data/nodes/sppuppet03test.domain.com.yaml"
          Original path: "nodes/%{::trusted.certname}.yaml"
          Path not found
      Hierarchy entry "Other YAML hierarchy levels"
        Path "/etc/puppetlabs/code/environments/stretch/data/common.yaml"
          Original path: "common.yaml"
          Path not found
Searching for "libnss-ldap_secret"
  Global Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
    Hierarchy entry "Hiera-vault lookup"
      Found key: "libnss-ldap_secret" value: "test"
      [hiera-vault] Client configured to connect to https://vault.domain.com:8200
      [hiera-vault] Looking in path secret/puppet/stretch/libnss-ldap_secret
      [hiera-vault] Looking in path secret/puppet/libnss-ldap_secret
      [hiera-vault] Read secret: libnss-ldap_secret

curl -v https://vault.domain.com:8200 -E /etc/puppetlabs/puppet/ssl/ssl_pem_file.pem --cacert /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
* Rebuilt URL to: https://vault.domain.com:8200/
*   Trying 10.99.4.100...
* TCP_NODELAY set
* Connected to vault.domain.com (10.99.4.100) port 8200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.domain.com
*  start date: Feb 20 18:58:38 2019 GMT
*  expire date: Apr 21 17:34:11 2020 GMT
*  subjectAltName: host "vault.domain.com" matched cert's "*.domain.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: vault.domain.com:8200
> User-Agent: curl/7.52.1
> Accept: */*

You have similar ticker, where lookup works but puppet agent doesn't, not sure if related.
Would you be able to help to found out the root cause ?

**Comment by petems** [comment]
I'm not sure whats happening there, Your listing shows `davealden-hiera_vault`

The version should be `petems-hiera_vault - 0.4.0`

Are you managing modules with R10k? Or just installed straight on the server?

**Comment by petersutty** [comment]
I just installed straight on the server:
puppet module install petems-hiera_vault-0.1.0.tgz --ignore-dependencies
--force --environment stretch

can I use 0.4.0 on vault k/v v1 ?

**Comment by petems** [comment]
Yes, you can use 0.4.0 with vault k/v1

Can you try installing 0.4.0 and trying again for me?

**Comment by petersutty** [comment]
puppet module list --environment stretch | grep vault
petems-hiera_vault (v0.4.1)

cat
/etc/puppetlabs/code/environments/stretch/modules/test/manifests/init.pp
 $secret = lookup({"name" => "libnss-ldap_secret" })
 notify {"testing vault ${secret}":}
 file { '/tmp/test':
       content => $secret,
 }
}

sudo puppet agent -tv --tags test
Error: Could not retrieve catalog from remote server: Error 500 on SERVER:
Server Error: Evaluation Error: Error while evaluating a Resource
Statement, Evaluation Error: Error while evaluati
ng a Function Call, Lookup of key 'libnss-ldap_secret' failed:
[hiera-vault] Skipping backend. Configuration error: Received fatal alert:
handshake_failure (file: /etc/puppetlabs/code/enviro
nments/stretch/modules/test/manifests/init.pp, line: 6, column: 13) on node
kicktest.domain.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

puppet lookup libnss-ldap_secret --explain
Thread.exclusive is deprecated, use Thread::Mutex
/etc/puppetlabs/code/environments/stretch/modules/common/lib/facter/partitions.rb:12:in
`<top (required)>'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:35:in
`to_hash'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:35:in
`find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:198:in
`find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node.rb:135:in
`fact_merge'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/node/plain.rb:18:in
`find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:198:in
`find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:345:in
`generate_scope'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:312:in
`main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:383:in
`run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in
`block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:667:in
`exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in
`run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:139:in
`run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in
`execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Searching for "lookup_options"
Global Data Provider (hiera configuration version 5)
  Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
  Hierarchy entry "Hiera-vault lookup"
    No such key: "lookup_options"
    [hiera-vault] Skipping hiera_vault backend because key 'lookup_options'
does not match confine_to_keys
Environment Data Provider (hiera configuration version 5)
  Using configuration
"/etc/puppetlabs/code/environments/stretch/hiera.yaml"
  Merge strategy hash
    Hierarchy entry "Per-node data (yaml version)"
      Path
"/etc/puppetlabs/code/environments/stretch/data/nodes/sppuppet03test.domain.com.yaml"

        Original path: "nodes/%{::trusted.certname}.yaml"
        Path not found
    Hierarchy entry "Other YAML hierarchy levels"
      Path "/etc/puppetlabs/code/environments/stretch/data/common.yaml"
        Original path: "common.yaml"
        Path not found
Searching for "libnss-ldap_secret"
Global Data Provider (hiera configuration version 5)
  Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
  Hierarchy entry "Hiera-vault lookup"
    Found key: "libnss-ldap_secret" value: "test"
    [hiera-vault] Client configured to connect to
https://vault.domain.com:8200
    [hiera-vault] Looking in path secret/puppet/stretch/libnss-ldap_secret
    [hiera-vault] Looking in path secret/puppet/libnss-ldap_secret
    [hiera-vault] Read secret: libnss-ldap_secret

cat /etc/puppetlabs/puppet/hiera.yaml
---
# Hiera 5 Global configuration file
# notice no TABs are allowed

version: 5

# defaults:
#   data_hash: yaml_data
# hierarchy:
#  - name: Common
#    data_hash: yaml_data
#hierarchy: []
hierarchy:
 - name: "Hiera-vault lookup"
   lookup_key: hiera_vault
   options:
     # Only use this backend if the key matches one of the regexes in the
array - related to performance - did not work with key.secret for me, had
to change to key_secret
     confine_to_keys:
       - ".*secret$"
       - ".*vault$"
     ssl_verify: false
     #ssl_pem_file: /etc/puppetlabs/puppet/ssl/ssl_pem_file.pem
     #ssl_ca_cert: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
     #ssl_ciphers: "MY:SSL:CIPHER:CONFIG"
     address: https://vault.domain.com:8200
     token: xxxxxxxxxxxxxxxxxxxxxx
     default_field: value
     mounts:
       secret:
         # we first check if we have environment specific key, otherwise
use common key
         - puppet/%{::environment}/
         - puppet/

just thinking loud - if "ssl_verify: false" means the same as
"-tls-skip-verify" in vault command ? as in our case vault without
-tls-skip-verify would fail with message like: x509: cannot validate
certificate for 127.0.0.1 because it doesn't contain any IP SANs - not sure
if related though ?

**Comment by petersutty** [comment]
Any update on this?

**Comment by traviscosgrave** [comment]
I experienced a similar issue when our Puppet Servers are trying to talk directly to Vault.

Check if you can use `puppet lookup` as this will use the Puppet Ruby gems (whereas Puppet Server is using JRuby gems).

If `puppet lookup` works fine (similar to your `curl`), then my next suggestion is to check the cipher suite of Vault against what the JRuby implemenetation of OpenSSL supports (https://github.com/jruby/jruby-openssl/issues/168) is realted.

To work around this, we run Vault in `agent` mode on the Puppet Servers and have them talk to local host an the Vault `agent` is happy to support the same ciphers as the Vault server.

**Comment by petersutty** [comment]
Bingo!
it was the cipher suite set on vault too hard:
tls_cipher_suites =
"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
If you comment it out it will add this cipher TLS_RSA_WITH_3DES_EDE_CBC_SHA
on vault, which is compatible with puppet server's JRuby.

Now just need to wait for this fix
https://github.com/jruby/jruby-openssl/pull/177

And thanks for the workaround tip, but I am running vault in internal
environment (not a public service), so I am good with that cipher
