### ISSUE TITLE
Sample vault secrets in README, Documentation of default_field_*

### ISSUE THREAD

**Issue by yakatz** [petems/petems-hiera_vault#46]
The documentation [currently talks about](https://github.com/petems/petems-hiera_vault/blob/master/README.md#mounts) creating a new mount for secrets that Puppet can access. It would be nice if the documentation also included some sample secrets that the supplied configuration could retrieve. It took me a long time to figure out how to set `hiera.yaml` and the secret being retrieved in the `lookup()` function to be able to access existing secrets, but if there were sample secrets in the documentation, we could just make sure we keep them like that.

Also as part of that searching, I stumbled across `default_field_behavior` and `default_field_parse`. I don't see any documentation of either of those two options. I can guess based on the code, but it would be nice to know for sure how they are intended to work.

**Comment by petems** [comment]
I've been meaning to overhaul the documentation for a while with examples, will see if I can add these details in soon! 😄

**Comment by petems** [comment]
I believe the docs have been updated to cover and explain all of this in #69, if not feel free to comment and we can re-open and discuss
