### ISSUE TITLE
Issue with lookup function 

### ISSUE THREAD

**Issue by Rahulgoyal17** [petems/petems-hiera_vault#48]
Hi Peter,
I am trying to integrate puppet with vault. 
I am using this hiera vault module for it. 
After integration when I am running lookup function from the puppet master I am able to fetch data from the vault however when I am trying it from agent node its not working.
I have tested it by using puppet agent and lookup function. 
Do I need to make any changes in the agent config?
I am using foreman as puppet master.

**Comment by petems** [comment]
Sorry for the late reply, can you show me the configuration you currently have? (redacted of secrets)

Whats the error you're getting? Is it an authorization failure, or an inability to find the secret that you can find during the master lookup

**Comment by petems** [comment]
Closing due to lack of response, feel free to re-open if answers avaliable.
