### ISSUE TITLE
vault caching

### ISSUE THREAD

**Issue by maxadamo** [petems/petems-hiera_vault#57]
hey @petems 
out of curiosity, is caching supported as described here: [Vault Agent Caching](https://www.vaultproject.io/docs/agent/caching) ?
is it supported by the vault gem? 
If it's supported by the ruby gem, are we using it in `hiera_vault` ? 

p.s.: this is somehow in between an information request and a feature request

**Comment by petems** [comment]
The gem doesn't require specific support for if, you can just run the agent caching on the machine and point it toward the local cache over the normal Vault cluster. 

I have done this with the new Puppet 6 lookup way: https://petersouter.xyz/vault-caching-with-auto-auth-and-puppet/

I haven't tried it with hiera_vault but in theory it could work

**Comment by maxadamo** [comment]
amazing! Thanks a lot for the info. 
I'm gonna close it.

**Comment by maxadamo** [comment]
it seems to be working, with one caveat. 
the token, in hiera.yaml must be set only as following (two quotes_:
```
token: ''
```

I have tried to undef the value (which is "null" in Yaml): `token: null` and it doesn't work. 
I have tried to comment out the whole line and it doesn't work.
