### ISSUE TITLE
When get the secrets if the secret contain a dollar (example$rest) sign only retrieve the secret until the dollar sign (example)

### ISSUE THREAD

**Issue by elserhumano** [petems/petems-hiera_vault#67]
When I get a secret from the Vault Server using hiera_vault if the secret contains a dollar sign (exampe$more-characters) the value returned is until the dollar sign (example), I use a lot to render ini/config files.

I use puppet 6.x as code and make a lab with Puppet Server Open Source.

I try a lot of things like escaped the dollar signs but doesn't work!

**Comment by petems** [comment]
Can you give me some example code of how this looks?

**Comment by elserhumano** [comment]
Hello Peter,

Sorry, I finally found a solution, the problem does not go through your
module, it was from a previous step that involved third-party encryption
software.

You can rule out this problem!

Thanks for following up on this issue!


Regards,
Fernando
