### ISSUE TITLE
changelog not updated for 2.0.0

### ISSUE THREAD

**Issue by TheMeier** [petems/petems-hiera_vault#72]
There is no changelog entry for release 2.0.0

**Comment by petems** [comment]
Fixed: https://github.com/petems/petems-hiera_vault/commit/82d667e1c1f620d6fc3993e93169a7e9bbd12acc

**Comment by arcenik** [comment]
Hi,

This is still  not visible on https://forge.puppet.com/modules/petems/hiera_vault/changelog

Best regards
